# Generated by Django 4.2 on 2023-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="num_bath_rooms",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="num_bed_rooms",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
