# Generated by Django 4.2 on 2023-04-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_platfroms_property_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platfroms",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
